pingcap/ng-monitoring

config/config.go, config/config_test.go
=> conprof: add more invalid config check

component/conprof/http/api.go, component/conprof/scrape/manager.go
=> don't scrap tiflash profile

component/topology/discovery.go, component/topsql/subscriber/subscriber.go, component/topsql/topsql.go, config/pdvariable/pdvariable.go, main.go
=> disable top sql by default & respect pd variable

database/timeseries/vm.go
=> fix unexpected last point filling

service/http/http.go
Signed-off-by: crazycs <chen.two.cs@gmail.com>
This api is same as PD.
```shell
▶ curl "127.0.0.1:12020/health"
{"health":true}%
```
=> add health api

config/config.go, config/config_test.go, database/document/document.go, database/document/logger.go, database/timeseries/vm.go, main.go, service/http/http.go
Signed-off-by: crazycs <chen.two.cs@gmail.com>
=> log: support stdout output log

component/topsql/subscriber/subscriber.go, database/timeseries/syscall_not_linux_unix.go
=> add keepalive for topsql subscriber

component/topology/syncer.go, config/config.go, config/config_test.go, main.go
close https://github.com/pingcap/ng-monitoring/issues/19
close https://github.com/pingcap/ng-monitoring/issues/24
close https://github.com/pingcap/ng-monitoring/issues/27
close https://github.com/pingcap/ng-monitoring/issues/28
=> refine unspecified pd endpoints error msg

Makefile, main.go, utils/printer/printer.go
close https://github.com/pingcap/ng-monitoring/issues/20
```log
[2021/12/10 17:10:38.792 +08:00] [INFO] [printer.go:23] ["Welcome to ng-monitoring."] ["Git Commit Hash"=c2b97282d0a4fd24091e478d53d06297329fd8fb] ["Git Branch"=welcome-msg] ["UTC Build Time"="2021-12-10 09:08:53"] [GoVersion=go1.16]
```
=> add welcome log info

component/conprof/store/gc.go, database/document/document.go
close https://github.com/pingcap/ng-monitoring/issues/32
=> do gc when ngm start

component/conprof/http/api.go, component/conprof/http/api_test.go
close https://github.com/pingcap/ng-monitoring/issues/46
=> conprof: support download data by time range

config/config.go, config/config_test.go
=> change def value of config.address

component/topology/syncer.go, component/topology/topology_test.go
Currently, ng-monitor topology key in etcd is different with TiDB:
```shell
▶ etcdctl --endpoints=10.0.1.11:20379 get "/topology/ng" --prefix
/topology/ng-monitoring/10.0.1.11:12020/ttl
1639638711375864489
▶ etcdctl --endpoints=10.0.1.11:20379 get "/topology/tidb" --prefix
/topology/tidb/10.0.1.11:4000/info
{"version":"v5.4.0-alpha-134-g276721877","git_hash":"276721877cf84c32ecacb6b2dcfea83ebbdeb8cf","ip":"10.0.1.11","status_port":10080,"deploy_path":"/home/vagrant/deploy/tidb-4000/bin","start_timestamp":1639638254,"labels":{}}
/topology/tidb/10.0.1.11:4000/ttl
1639638704697655900
```
This PR add server info key into etcd, to make consistence with TiDB.
```shell
/topology/ng-monitoring/192.168.1.3:12020/info …
```
=> topology: add server info to keep consistence with TiDB

component/topsql/mock/mem_store.go, component/topsql/mock/pubsub/tidb.go, component/topsql/mock/pubsub/tikv.go, component/topsql/subscriber/manager.go, component/topsql/subscriber/scraper.go, component/topsql/subscriber/scraper_test.go, config/config.go, go.sum
=> topsql: add scraper tests

component/conprof/http/api.go, component/conprof/scrape/manager.go, component/conprof/scrape/manager_test.go
=> support profiling tiflash

component/topsql/subscriber/scraper.go, component/topsql/subscriber/scraper_test.go
=> topsql: cover scraper 70%

component/conprof/http/api_test.go, component/conprof/store/store.go
=> conprof: add query time range check and remove default limit 100

component/conprof/scrape/manager.go, component/domain/domain.go, component/topsql/subscriber/default_subscriber.go, component/topsql/subscriber/manager.go, component/topsql/subscriber/scraper.go, component/topsql/subscriber/scraper_test.go, component/topsql/topsql.go, config/config.go, config/config_test.go, main.go, tests/topsql_test.go
=> *: add config subscriber

component/conprof/README.md, component/conprof/http/api.go, component/conprof/http/api_test.go
```shell
▶ curl "http://192.168.1.3:12020/continuous_profiling/download?ts=1639733820&profile_type=profile&component=pd&address=10.0.1.11:21379&data_format=protobuf" > profile.zip
▶ unzip profile.zip
Archive:  profile.zip
inflating: profile_pd_10.0.1.11_21379_1639733820
```
=> conprof: support download single profile and tiny refact

.github/pull_request_template.md
=> github: add pull_request_template.md

component/conprof/scrape/manager.go, component/conprof/scrape/manager_test.go, component/conprof/scrape/scrape.go, component/conprof/store/gc.go, component/conprof/store/store.go, component/conprof/store/store_test.go, component/conprof/util/misc.go
close https://github.com/pingcap/ng-monitoring/issues/31
=> remove meanless function

component/conprof/http/api.go, component/conprof/http/api_test.go, component/conprof/scrape/manager.go, component/conprof/scrape/manager_test.go, component/conprof/scrape/scrape.go, component/conprof/scrape/ticker.go
close https://github.com/pingcap/ng-monitoring/issues/35
```shell
▶ curl "http://192.168.1.3:12020/continuous_profiling/group_profiles?begin_time=1639725850&end_time=1644836910"
[{"ts":1639725960,"profile_duration_secs":10,"state":"running","component_num":{"tidb":1,"pd":3,"tikv":0,"tiflash":0}}]% 
```
This PR also need to change the tidb-dashboard.
=> fix bug of running state instead of finished state

component/conprof/http/api.go, component/conprof/http/api_test.go
=> conprof: refine download api and add readme.md in download zip file

component/topsql/query/default_query.go, component/topsql/query/default_query_test.go, component/topsql/query/query.go, component/topsql/service/http.go, tests/topsql_test.go
Issue Number: close #78 
`Others` is not implemented.
Accumulate excluded values
=> topsql: fix others by accumulate excluded values

component/topsql/mock/mem_store.go, component/topsql/service/pools.go, component/topsql/store/default_store.go, component/topsql/subscriber/scraper_test.go, go.mod, go.sum, tests/topsql_test.go
Ref https://github.com/tikv/tikv/issues/11748
Upgrade `kvproto` to https://github.com/pingcap/kvproto/pull/847
- https://github.com/pingcap/kvproto/pull/847
- https://github.com/tikv/tikv/pull/11749
=> upgrade kvproto

component/topsql/query/default_query.go, component/topsql/query/model.go, component/topsql/query/pools.go, component/topsql/query/query.go, component/topsql/service/http.go, component/topsql/service/pools.go, component/topsql/store/default_store.go, component/topsql/store/model.go, component/topsql/topsql_test.go, tests/topsql_test.go
Issue Number: close #83 
`Query` interface:
* Add `Summary` method
* Rename `TopSQL` to `Records`
=> topsql: add summary service

component/topsql/query/default_query.go, component/topsql/query/model.go, component/topsql/query/pools.go, component/topsql/topsql_test.go
Issue Number: close #84
Scan all sum records. Sum up evicted records to others.
=> topsql: add exec count & duration for others

component/topsql/query/default_query.go, component/topsql/query/pools.go
=> topsql: fix reuse decode struct

component/topsql/query/default_query.go
=> topsql: fix other index

component/topsql/query/default_query.go, component/topsql/query/model.go, component/topsql/topsql_test.go
=> topsql: add overall fields for summary

component/conprof/http/api.go
=> conprof: update download readme

component/topsql/query/default_query.go, component/topsql/query/model.go, component/topsql/service/http.go, component/topsql/store/default_store.go, component/topsql/store/model.go, component/topsql/topsql_test.go, go.mod, go.sum
Issue Number: close https://github.com/pingcap/ng-monitoring/issues/97
- https://github.com/pingcap/tipb/pull/253
- https://github.com/pingcap/tidb/pull/31378
=> topsql: add exec count dedicated to sql duration

main.go, utils/printer/printer.go
Issue Number: close #89
```shell
▶ bin/ng-monitoring-server -V
Git Commit Hash: 82efa9b66685d9f416d97b5c903d95cfce8c64da
Git Branch: print-version
UTC Build Time: 2022-01-12 06:39:43
GoVersion: go1.16
```
```shell
▶ bin/ng-monitoring-server --version
Git Commit Hash: 82efa9b66685d9f416d97b5c903d95cfce8c64da
Git Branch: print-version
UTC Build Time: 2022-01-12 06:39:43
GoVersion: go1.16
```
=> *: support print version flag

component/topsql/topsql_test.go
=> topsql: add test case for same ts but different scan type

component/conprof/http/api.go, component/conprof/http/api_test.go, component/conprof/meta/meta.go, component/conprof/scrape/manager.go, component/conprof/scrape/scrape.go, component/conprof/store/store.go, component/conprof/store/store_test.go, component/topsql/topsql_test.go
=> conprof: store profile status

component/conprof/store/store.go
```shell
--- FAIL: TestProfileStorage (0.54s)
store_test.go:111:
Error Trace:    store_test.go:111
store_test.go:29
Error:          Not equal:
expected: 1644219544
actual  : 1644219543
Test:           TestProfileStorage
```
=> conprof: fix unstable test 

component/conprof/http/api.go, component/conprof/meta/meta.go, component/conprof/meta/meta_test.go, component/conprof/scrape/manager.go, component/conprof/scrape/manager_test.go, component/conprof/scrape/scrape.go
=> conprof: fix running status when cluster running without TiKV 

component/conprof/store/store_test.go, database/timeseries/syscall_not_linux_unix.go, go.mod, go.sum
cherry-pick https://github.com/pingcap/ng-monitoring/pull/119
close https://github.com/pingcap/ng-monitoring/issues/120
=> conprof: fix genjidb(badger) gc doesn't work problem (#119)

component/conprof/http/api_test.go, component/conprof/scrape/manager.go, component/conprof/scrape/manager_test.go, component/conprof/store/store_test.go, component/domain/client.go, component/domain/domain.go, component/domain/domain_test.go, component/topology/topology_test.go, component/topsql/subscriber/default_subscriber.go, component/topsql/subscriber/default_subscriber_test.go, component/topsql/subscriber/manager.go, component/topsql/subscriber/manager_test.go, component/topsql/topsql.go, config/config.go, config/config_test.go, config/pdvariable/pdvariable_test.go, config/service_test.go, main.go, tests/topsql_test.go
=> config: try best to notify subscriber and always return the latest value

component/conprof/http/api_test.go, component/conprof/scrape/manager.go, component/conprof/scrape/manager_test.go, component/conprof/store/store_test.go, component/topology/discovery.go, component/topology/topology.go, component/topology/topology_test.go, component/topsql/subscriber/default_subscriber_test.go, component/topsql/subscriber/manager.go, component/topsql/subscriber/manager_test.go, config/config_test.go, tests/topsql_test.go
Same reason as https://github.com/pingcap/ng-monitoring/pull/122
=> topo: try best to notify subscriber and always return the latest value

config/config.go
=> enable conprof by default

component/conprof/http/api.go, component/conprof/scrape/manager.go, component/conprof/scrape/manager_test.go
Issue Number: close #xxx
cherry-pick https://github.com/pingcap/ng-monitoring/pull/118
=> Revert "support profiling tiflash (#47)" (#118)

component/conprof/store/store_test.go, database/document/document.go, database/document/document_test.go, database/document/gc.go, database/timeseries/syscall_not_linux_unix.go, go.mod, go.sum, utils/testutil/util.go
Issue Number: close #xxx
cherry-pick https://github.com/pingcap/ng-monitoring/pull/115
https://github.com/pingcap/ng-monitoring/pull/119
=> conprof: fix genjidb(badger) gc doesn't work problem(#115)(#119)

.github/workflows/ci.yml
=> test: add github action for ci

component/conprof/http/api.go, component/conprof/scrape/manager.go, component/conprof/scrape/manager_test.go
Issue Number: close #133
This PR should be merged after them:
- https://github.com/pingcap/tidb-engine-ext/pull/60
- https://github.com/pingcap/tidb-engine-ext/pull/61
- https://github.com/pingcap/tiflash/pull/4871
=> conprof: enable profiling tiflash

go.mod, go.sum
=> Update ristretto to fix deadlock on ARM

config/config.go, config/config_test.go, config/persist.go, config/service.go, config/service_test.go, main.go
Issue Number: close #136
1. Add function `UpdateGlobalConfig`
2. Use mutex to protect global config
=> config: fix update conflict causing by http API and file reload

config/config.go, config/config_test.go
=> conprof: disable continuous profiling by default

config/pdvariable/pdvariable.go
Issue Number: close #164
Fix variable shadowed
=> pdvariable: fix panic caused by shadowed variable

component/conprof/http/api.go, component/conprof/scrape/manager.go, component/topology/discovery.go
Issue Number: ref #166
- Add TiCDC to the ng-monitoring backend (Step 1 in the associated issue: #166).
=> conprof: support ticdc backend

.github/workflows/ci.yml, Makefile, go.mod, service/http/http.go, utils/testutil/util.go
=> upgrade go 1.20.1

.github/workflows/ci.yml, go.mod
=> upgrade go version to 1.21

component/conprof/jeprof/jeprof.go
Issue Number: ref https://github.com/pingcap/ng-monitoring/issues/197
reuse `convertDotToSVG` to avoid the dependency of `graphviz` in env
=> conprof: reuse convertDotToSVG to generate tikv heap profile svg

OWNERS
Issue Number: close #209 
Add the following github accounts to owners:
- zhangpeijin-milo
- z2665
- just1900
=> OWNERS: add TiDB cloud o11y team to owners

Makefile, config/config.go, config/config_test.go
Issue Number: close #225
- Upgrade `golangci-lint`.
- Little fixes on comments.
=> *: update golangci-lint version to fix ci

config/config.go, config/config.toml.example, config/config_test.go, database/document/document.go
Issue Number: ref https://github.com/pingcap/ng-monitoring/issues/230
1. Expose almost all badger db options to ngm's config.
2. Adjust some options to the defaults of badger.
=> docdb: expose almost all options to user

README.md
=> chore: add placeholder version in README.md

service/http/http.go
Issue Number: close https://github.com/pingcap/ng-monitoring/issues/255
We should match the `gin` routers first, then handle by VMMetrics' API handlers.
before:
it will match the vminsert.RequestHandler, returns empty with status 202. no gin log output.
after
victoria-metrics also works:
and dashboard continous_profile can works:
=> api:  Fix the  api to ensure it works correctly.

component/topsql/query/default_query.go, component/topsql/query/model.go, component/topsql/query/query.go, component/topsql/service/http.go, component/topsql/service/pools.go, component/topsql/topsql_test.go
Issue Number: close https://github.com/pingcap/ng-monitoring/issues/266 ref https://github.com/pingcap/tidb/issues/55540
=> topsql: add backend of group by table or db

.golangci.yml, Makefile, go.mod
Issue Number: close #263
Upgrade to go1.23
=> *: upgrade to go1.23

component/subscriber/manager.go
Issue Number: close https://github.com/pingcap/ng-monitoring/issues/275
=> subscriber/manager: reduce the update schema interval

database/docdb/docdb_test.go, database/docdb/genji_test.go, database/docdb/sqlite_test.go
Issue Number: ref #267
This PR is a supplement to #287 and only includes unit tests.
=> docdb: add unit tests

go.mod, go.sum
=> Update image lib version due to secrity issue

OWNERS, go.mod
Issue Number: close #310 
BTW, add observability team members as owner.
=> update go version to 1.24.6 to fix security issue
